spring.application.name=lab05.demo
spring.datasource.url=jdbc:postgresql://db.rjsrjqlpodufmtdezzyt.supabase.co:5432/postgres?user=postgres&password=Lemafevis2jesus!
# spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
